export const fakeDB = [
  { _id: '01', name: 'Alice' },
  { _id: '02', name: 'Bob' },
  { _id: '03', name: 'Charlie' },
  { _id: '04', name: 'David' },
  { _id: '05', name: 'Eve' },
  { _id: '06', name: 'Frank' },
  { _id: '07', name: 'Grace' },
  { _id: '08', name: 'Hank' },
  { _id: '09', name: 'Ivy' },
  { _id: '10', name: 'Jack' },
  { _id: '11', name: 'Kathy' },
  { _id: '12', name: 'Leo' },
  { _id: '13', name: 'Mona' },
  { _id: '14', name: 'Nina' },
  { _id: '15', name: 'Oscar' },
  { _id: '16', name: 'Paul' },
  { _id: '17', name: 'Quincy' },
  { _id: '18', name: 'Rachel' },
  { _id: '19', name: 'Steve' },
  { _id: '20', name: 'Tracy' },
  { _id: '21', name: 'Uma' },
  { _id: '22', name: 'Victor' },
  { _id: '23', name: 'Wendy' },
  { _id: '24', name: 'Xander' },
  { _id: '25', name: 'Yara' },
  { _id: '26', name: 'Zane' },
];
