name: Publish
on:
  push:
    branches:
      - master
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout pnpm repo
        uses: chlbri/pnpmi-action@main

      - name: Build
        run: pnpm run build

      - uses: chlbri/npm-publish-action@main
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          strategy: upgrade

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key:
            ${{ runner.os }}-pnpm-store-${{
            hashFiles('**/pnpm-lock.yaml')}}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm run build

      - uses: JS-DevTools/npm-publish@v3
        id: publish
        name: Publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          strategy: upgrade

      - name: Check - updated
        if: ${{ steps.publish.outputs.type }}
        run:
          echo "${{ steps.publish.outputs.name }} Version changed from ${{
          steps.publish.outputs.old-version }} to ${{
          steps.publish.outputs.version }}"

      - name: Check - not updated
        if: ${{ ! steps.publish.outputs.type }}
        run: echo "Remain the same! - ${{ steps.publish.outputs.version }}"
